apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-listener
  template:
    metadata:
      labels:
        app: logstash-listener
        deploy_date_time: '20240726_150452'
    spec:
      serviceAccountName: kafkaserviceacct
      volumes:
      - name: logstash-config-volume
        configMap:
          name: 'logstash-listener-config'
          items:
            - key: logstash.yml
              path: logstash.yml
            - key: pipelines.yml
              path: pipelines.yml
            - key: log4j2.properties
              path: log4j2.properties
      - name: logstash-pipeline-volume
        configMap:
          name: 'logstash-listener-pipeline'
          items:
            - key: pipeline.conf
              path: pipeline.conf
            - key: filter.rb
              path: filter.rb
      containers:
      - name: logstash
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 1G
        envFrom:
          - configMapRef:
              name: logstash-listener
        env:
          - name: deploy_date_time
            value: '20240726_150452'  
        image: 872859983801.dkr.ecr.ca-central-1.amazonaws.com/logstash:8.11.1
        # command: ["tail","-f","/dev/null"]
        volumeMounts:
          - name: logstash-config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
