apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0744c3d1cf3c4b01c, subnet-063f90f66f30aa773
    service.beta.kubernetes.io/aws-load-balancer-type: external
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - service.k8s.aws/resources
  name: logstash-httpinput-external-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: logstash-listener  
  sessionAffinity: None
  type: LoadBalancer
