apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{THOR_LOGSTASH_APP}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{THOR_LOGSTASH_APP}}
  template:
    metadata:
      labels:
        app: {{THOR_LOGSTASH_APP}}
        deploy_date_time: '{{DEPLOY_DATE_TIME}}'
    spec:
      serviceAccountName: kafkaserviceacct
      volumes:
      - name: logstash-pvc-volume
        persistentVolumeClaim:
          claimName: logstash-pvc      
      - name: logstash-config-volume
        configMap:
          name: '{{THOR_LOGSTASH_APP}}-config'
          items:
            - key: logstash.yml
              path: logstash.yml
            - key: pipelines.yml
              path: pipelines.yml
            - key: log4j2.properties
              path: log4j2.properties
            - key: aws.cer.txt
              path: aws.cer.txt
            - key: aws.pk.txt
              path: aws.pk.txt
      - name: logstash-pipeline-volume
        configMap:
          name: '{{THOR_LOGSTASH_APP}}-pipeline'
          items:
            - key: pipeline.conf
              path: pipeline.conf
            - key: filter.rb
              path: filter.rb
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R 777 /mnt/pvc']
          volumeMounts:
            - mountPath: /mnt/pvc
              name: logstash-pvc-volume      
      containers:
      - name: logstash
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 1G
        envFrom:
          - configMapRef:
              name: {{THOR_LOGSTASH_APP}}
        env:
          - name: deploy_date_time
            value: '{{DEPLOY_DATE_TIME}}'  
        image: 872859983801.dkr.ecr.ca-central-1.amazonaws.com/logstash:8.11.1
        # command: ["tail","-f","/dev/null"]
        volumeMounts:
          - name: logstash-config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
          - mountPath: /mnt/pvc
            name: logstash-pvc-volume