apiVersion: v1
kind: Service
metadata:
  name: gtw-syslog-listener-local
spec:
  selector:
    app: gtw-syslog-listener
  ports:
    - protocol: TCP
      port: 31500
      targetPort: 31500
      name: syslog-port
    - protocol: TCP
      port: 31501
      targetPort: 31501
      name: http-port
