apiVersion: v1
kind: Service
metadata:
  name: gtw_syslog_listener_local
spec:
  selector:
    app: gtw-syslog-listener
  ports:
    - protocol: TCP
      port: 31500
      targetPort: 31500
    - protocol: TCP
      port: 31501
      targetPort: 31501
