apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{THOR_LOGSTASH_APP}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{THOR_LOGSTASH_APP}}
  template:
    metadata:
      labels:
        app: {{THOR_LOGSTASH_APP}}
        deploy_date_time: '{{DEPLOY_DATE_TIME}}'
    spec:
      serviceAccountName: kafkaserviceacct
      volumes:
      - name: logstash-pvc-volume
        persistentVolumeClaim:
          claimName: kafka-pvc
      - name: logstash-config-volume
        configMap:
          name: '{{THOR_LOGSTASH_APP}}-config'
          items:
            - key: logstash.yml
              path: logstash.yml
            - key: pipelines.yml
              path: pipelines.yml
            - key: log4j2.properties
              path: log4j2.properties
      - name: logstash-pipeline-volume
        configMap:
          name: '{{THOR_LOGSTASH_APP}}-pipeline'
          items:
            - key: kafka.conf
              path: kafka.conf
            - key: kafka-filter.rb
              path: kafka-filter.rb
      containers:
      - name: logstash
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 1G
        envFrom:
          - configMapRef:
              name: {{THOR_LOGSTASH_APP}}
        env:
          - name: deploy_date_time
            value: '{{DEPLOY_DATE_TIME}}'  
        image: 872859983801.dkr.ecr.ca-central-1.amazonaws.com/logstash:8.14.3
        volumeMounts:
          - name: logstash-config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
          - mountPath: /mnt/pvc
            name: logstash-pvc-volume            
